### ISSUE TITLE
About robust_finetuning

### ISSUE THREAD

**Issue by KU-HJH** [valentyn1boreiko/DVCEs#1]
Thank you for releasing great works!

I think the environment named robust_finetuning is missing in your setup script.

Can you please provide guidance for installing the framework about robust_finetuning??

**Comment by valentyn1boreiko** [comment]
Hi Martin,

thank you for your interest! 

This was not a crucial dependency, and we have removed it recently. I have changed the code respectively, tested it and pushed it. Please, let me know, if it resolved the issue.

**Comment by KU-HJH** [comment]
Thanks so much for your kind explanation.

I successfully ran this code without issues.

Until success in running, I share issues faced before success in running: 
1. There is an issue while loading the model onto the GPU (python gets stuck while loading).
2. Dataset path addressed by an argument is not delivered to the ImageNetDataset module.

And here is the solution I have:
1. Employing python without conda & downgrading Pytorch from 1.10 to the 1.9 
2. Modified get_base_data_dir() to receive the argument of the dataset path.

Thank you again for your guidance, and I hope such tips can help release the code.

**Comment by valentyn1boreiko** [comment]
I am glad it resolved the issue and you could run it. Enjoy the code and let me know, if other help is needed! I will close this issue then.
